-- MySQL Script generated by MySQL Workbench
-- Wed Aug 15 11:05:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbsistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistema` DEFAULT CHARACTER SET utf8 ;
USE `dbsistema` ;

-- -----------------------------------------------------
-- Table `dbsistema`.`tipo_movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`tipo_movimiento` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
--  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistema`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
--  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `primer_apellido` VARCHAR(30) NOT NULL,
  `segundo_apellido` VARCHAR(30) NOT NULL,
--  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `ciudad` VARCHAR(30) NOT NULL, 
  `direccion` VARCHAR(70) NOT NULL, 
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbsistema`.`cliente`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dbsistema`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `idpersona` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_persona_idx` (`idpersona`, ASC),
  CONSTRAINT `fk_cliente_persona`
    FOREING KEY (`idpersona`)
    REFERENCES `dbsistema`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbsistema`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
--  `nombre` VARCHAR(100) NOT NULL,
--  `tipo_documento` VARCHAR(20) NOT NULL,
--  `num_documento` VARCHAR(20) NOT NULL,
--  `direccion` VARCHAR(70) NULL,
--  `telefono` VARCHAR(20) NULL,
--  `email` VARCHAR(50) NULL,
  `cargo` VARCHAR(20) NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistema`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistema`.`cuenta` (
  `idcuenta` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idempleado` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
